require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CaseStudiesController do
  render_views

  # This should return the minimal set of attributes required to create a valid
  # CaseStudy. As you add validations to CaseStudy, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    FactoryGirl.attributes_for(:case_study, :language_id => FactoryGirl.create(:language).id)
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CaseStudiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all case_studies as @case_studies" do
      case_study = CaseStudy.create! valid_attributes
      get :index, {}
      assigns(:case_studies).should eq([case_study])
    end
  end

  describe "GET show" do
    it "assigns the requested case_study as @case_study" do
      case_study = CaseStudy.create! valid_attributes
      get :show, {:id => case_study.to_param}
      assigns(:case_study).should eq(case_study)
    end
  end

  describe "GET new" do
    login_admin

    it "assigns a new case_study as @case_study" do
      get :new, {}
      assigns(:case_study).should be_a_new(CaseStudy)
    end
  end

  describe "GET edit" do
    login_admin

    it "assigns the requested case_study as @case_study" do
      case_study = CaseStudy.create! valid_attributes
      get :edit, {:id => case_study.to_param}
      assigns(:case_study).should eq(case_study)
    end
  end

  describe "POST create" do
    login_admin

    describe "with valid params" do
      it "creates a new CaseStudy" do
        expect {
          post :create, {:case_study => valid_attributes}
        }.to change(CaseStudy, :count).by(1)
      end

      it "assigns a newly created case_study as @case_study" do
        post :create, {:case_study => valid_attributes}
        assigns(:case_study).should be_a(CaseStudy)
        assigns(:case_study).should be_persisted
      end

      it "redirects to the created case_study" do
        post :create, {:case_study => valid_attributes}
        response.should redirect_to(CaseStudy.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved case_study as @case_study" do
        # Trigger the behavior that occurs when invalid params are submitted
        CaseStudy.any_instance.stub(:save).and_return(false)
        post :create, {:case_study => {}}
        assigns(:case_study).should be_a_new(CaseStudy)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CaseStudy.any_instance.stub(:save).and_return(false)
        post :create, {:case_study => {}}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    login_admin

    describe "with valid params" do
      it "updates the requested case_study" do
        case_study = CaseStudy.create! valid_attributes
        # Assuming there are no other case_studies in the database, this
        # specifies that the CaseStudy created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CaseStudy.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => case_study.to_param, :case_study => {'these' => 'params'}}
      end

      it "assigns the requested case_study as @case_study" do
        case_study = CaseStudy.create! valid_attributes
        put :update, {:id => case_study.to_param, :case_study => valid_attributes}
        assigns(:case_study).should eq(case_study)
      end

      it "redirects to the case_study" do
        case_study = CaseStudy.create! valid_attributes
        put :update, {:id => case_study.to_param, :case_study => valid_attributes}
        response.should redirect_to(case_study)
      end
    end

    describe "with invalid params" do
      it "assigns the case_study as @case_study" do
        case_study = CaseStudy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CaseStudy.any_instance.stub(:save).and_return(false)
        put :update, {:id => case_study.to_param, :case_study => {}}
        assigns(:case_study).should eq(case_study)
      end

      it "re-renders the 'edit' template" do
        case_study = CaseStudy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CaseStudy.any_instance.stub(:save).and_return(false)
        put :update, {:id => case_study.to_param, :case_study => {}}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    login_admin

    it "destroys the requested case_study" do
      case_study = CaseStudy.create! valid_attributes
      expect {
        delete :destroy, {:id => case_study.to_param}
      }.to change(CaseStudy, :count).by(-1)
    end

    it "redirects to the case_studies list" do
      case_study = CaseStudy.create! valid_attributes
      delete :destroy, {:id => case_study.to_param}
      response.should redirect_to(case_studies_path)
    end
  end

end
