require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StaffController do

  # This should return the minimal set of attributes required to create a valid
  # Staff. As you add validations to Staff, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      :user_id => 1
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StaffController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  login_admin

  describe "GET index" do
    it "assigns all staff as @staff" do
      staff = Staff.create! valid_attributes
      get :index, {}
      assigns(:staff).should eq([staff])
    end
  end

  describe 'POST create' do
    describe "with valid params" do
      it "creates a new Staff" do
        expect {
          post :create, {:staff => valid_attributes.merge(:user_id => User.first.id)}
        }.to change(Staff, :count).by(1)
      end

      it "assigns a newly created staff as @staff" do
        post :create, {:staff => valid_attributes.merge(:user_id => User.first.id)}
        assigns(:staff).should be_a(Staff)
        assigns(:staff).should be_persisted
      end

      it "redirects to the staff user" do
        post :create, {:staff => valid_attributes.merge(:user_id => User.first.id)}
        response.should redirect_to user_path(assigns(:staff).user_id)
      end
    end
    
    describe "with invalid params" do
      it "assigns a newly created but unsaved staff as @staff" do
        # Trigger the behavior that occurs when invalid params are submitted
        Staff.any_instance.stub(:save).and_return(false)
        post :create, {:staff => {}}
        assigns(:staff).should be_a_new(Staff)
      end

      it "redirects to users path" do
        # Trigger the behavior that occurs when invalid params are submitted
        Page.any_instance.stub(:save).and_return(false)
        post :create, {:page => {}}
        response.should redirect_to users_path
      end
    end
  end

  describe "DELETE destroy" do
    before :each do
      @staff = FactoryGirl.create :staff
    end

    it "destroys the requested staff" do
      expect {
        delete :destroy, :id => @staff.id
      }.to change(Staff, :count).by(-1)
    end

    it 'should not destroy the user' do
      expect {
        delete :destroy, :id => @staff.id
      }.to change(User, :count).by(0)
    end

    it "redirects to the staff list" do
      delete :destroy, :id => @staff.id
      response.should redirect_to(user_path(@staff.user))
    end
  end

end
